### ISSUE TITLE
kicad-cli?

### ISSUE THREAD

**Issue by MarcelRobitaille** [flathub/org.kicad.KiCad#166]
Is it possible to launch `kicad-cli` from this package? I do not see it bundled as its own flatpak.

**Comment by jmaibaum** [comment]
Try running it as follows

```console
flatpak run --command=kicad-cli org.kicad.KiCad
```

You should be able to set this up as an alias.

**Comment by jmaibaum** [comment]
Closing this now. If your issue is not yet solved, feel free to re-open with further info.

**Comment by MarcelRobitaille** [comment]
@jmaibaum  Sorry, didn't have a chance to try it until just now. Works perfectly. Thank you!
