### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by hfiguiere** [flathub/org.kicad.KiCad#46]
the build failed **on aarch64** because it seems that the documentation tarball at https://kicad-downloads.s3.cern.ch/docs/kicad-doc-6.0.2.tar.gz did change and has a different checksum.

(it's `a8be2b4fec78783be1c4653f6571ff431f659fd58daf6f74a0427c4472d56b29` now)

As to the reason it did work on x86_64 it's probably because it is still cached.

Not sure what happened to be honest.

**Comment by jmaibaum** [comment]
The docs tarball did really change again shortly after tagging, see https://lists.launchpad.net/kicad-developers/msg45585.html

I was preparing the update with the old tarball. An update will follow shortly.
